apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}
  labels:
    chart: "{{ .Chart.Name | trunc 63 }}"
    chartVersion: "{{ .Chart.Version | trunc 63 }}"
    visualize: "true"
    app: {{ .Values.service.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
        visualize: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ .Values.service.name }}
            topologyKey: "kubernetes.io/hostname"
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
      - name: {{ .Values.service.name }}
        image: "{{ .Values.image.repository }}:{{ .Chart.Version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: ELASTICSEARCH_SAPI_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: aws.content.elasticsearch.v2.endpoint
        - name: ELASTICSEARCH_REGION
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: aws.region
        - name: OPA_URL
          value: "{{ .Values.env.opaURL }}"
        - name: FILTER_SV_POLICY_PATH
          value: "{{ .Values.env.filterSVPolicyPath }}"
        - name: ELASTICSEARCH_SAPI_INDEX
          value: "{{ .Values.env.ELASTICSEARCH_SAPI_INDEX }}"
        - name: KAFKA_CONSUMER_GROUP
          value: {{ .Values.service.name }}
        - name: KAFKA_TOPIC
          value: {{ .Values.env.KAFKA_TOPIC }}
        - name: KAFKA_TOPIC_OFFSET_FETCH_INTERVAL
          value: "{{ .Values.env.KAFKA_TOPIC_OFFSET_FETCH_INTERVAL }}"
        - name: KAFKA_TOPIC_LAG_TOLERANCE
          value: "{{ .Values.env.KAFKA_TOPIC_LAG_TOLERANCE }}"
        - name: KAFKA_ADDR
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: msk.kafka.broker.url
        - name: PUBLIC_CONCORDANCES_ENDPOINT
          value: "{{ .Values.env.PUBLIC_CONCORDANCES_ENDPOINT }}"
        - name: "BASE_API_URL"
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: api.host.with.protocol
        - name: KAFKA_CLUSTER_ARN
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: msk.kafka.cluster.arn
        ports:
        - containerPort: 8080
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: "/__gtg"
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 30
        resources:
{{ toYaml .Values.resources | indent 12 }}
      {{- if .Values.openPolicyAgentSidecar }}
      - name: "{{ .Values.openPolicyAgentSidecar.name }}"
        image: "{{ .Values.openPolicyAgentSidecar.repository }}:{{ .Values.openPolicyAgentSidecar.tag }}"
        imagePullPolicy: {{ .Values.openPolicyAgentSidecar.pullPolicy }}
        env:
          - name: POLICY_BUCKET
            valueFrom:
              configMapKeyRef:
                name: global-config
                key: opa.policy2.bucket
        ports:
          - name: http
            containerPort: 8181
        livenessProbe:
          httpGet:
            path: /health
            scheme: HTTP
            port: 8181
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health?bundle=true
            scheme: HTTP
            port: 8181
          initialDelaySeconds: 5
          periodSeconds: 10
        args:
          - "run"
          - "--ignore=.*"
          - "--server"
          - "--log-level=error"
          - "--log-format=json"
          - "--set=services.bundlesS3Bucket.url=$(POLICY_BUCKET)"
          - "--set=services.bundlesS3Bucket.credentials.s3_signing.web_identity_credentials.aws_region=$(AWS_REGION)"
          - "--set=bundles.contentRWElasticsearch.service=bundlesS3Bucket"
          - "--set=bundles.contentRWElasticsearch.resource=content-rw-elasticsearch.bundle.tar.gz"
          - "--set=bundles.contentRWElasticsearch.polling.min_delay_seconds=120"
          - "--set=bundles.contentRWElasticsearch.polling.max_delay_seconds=300"
      {{- end}}