
[[constraint]]
  name = "github.com/Financial-Times/go-fthealth"
  version = "0.5.0"

[[constraint]]
  name = "github.com/Financial-Times/go-logger"
  version = "1.0.0"

[[constraint]]
  name = "github.com/Financial-Times/message-queue-gonsumer"
  version = "0.4.2"

[[constraint]]
  name = "github.com/Financial-Times/service-status-go"
  version = "0.1.0"

[[constraint]]
  name = "github.com/Financial-Times/uuid-utils-go"
  version = "1.0.1"

[[constraint]]
  branch = "master"
  name = "github.com/dchest/uniuri"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[[constraint]]
  name = "github.com/jawher/mow.cli"
  version = "1.0.4"

[[constraint]]
  name = "github.com/pborman/uuid"
  version = "1.1.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/smartystreets/go-aws-auth"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/stretchr/stew"

[[constraint]]
  name = "gopkg.in/olivere/elastic.v2"
  version = "2.0.61"

[prune]
  go-tests = true
  unused-packages = true
