# Values used for the deployed application.
replicaCount: 0
service:
  name: content-rw-elasticsearch-reindexer
env:
  KAFKA_TOPIC: ForcedCombinedPostPublicationEvents
  KAFKA_CONCURRENT_PROCESSING: false
  PUBLIC_CONCORDANCES_ENDPOINT: http://public-concordances-api:8080
