# Values used for the deployed application.
replicaCount: 2
service:
  name: content-rw-elasticsearch
env:
  KAFKA_TOPIC: CombinedPostPublicationEvents
  PUBLIC_CONCORDANCES_ENDPOINT: http://public-concordances-api:8080
  INTERNAL_CONTENT_API_URL: http://internal-content-api:8080
