# Default values for content-rw-elasticsearch.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "true"
serviceAccountName: eksctl-content-rw-elasticsearch-serviceaccount
replicaCount: 2
image:
  repository: coco/content-rw-elasticsearch
  version: "" # should be set explicitly at installation
  pullPolicy: IfNotPresent
openPolicyAgentSidecar:
  name: open-policy-agent
  repository: openpolicyagent/opa
  tag: 0.62.1
  pullPolicy: IfNotPresent
serviceAccount: eksctl-content-rw-neo4j-serviceaccount
resources:
  requests:
    memory: 64Mi
  limits:
    memory: 512Mi
env:
  KAFKA_TOPIC: ""
  PUBLIC_CONCORDANCES_ENDPOINT: ""
  ELASTICSEARCH_SAPI_INDEX: "ft-v1"
